background = 0xFF2E3440        
base = 0xFF111827              
alternate_base = 0xFF1B242B    

text = 0xFFFFFFFF              
bright_text = 0xFFCAD3F5       

accent = 0xFF8968CD            
accent_secondary = 0xFF6A92D7  

font_family = Fira Sans Semibold
font_family_monospace = monospace

font_size = 12
small_font_size = 10

h1_size = 19
h2_size = 15
h3_size = 13

icon_theme = 

rounding_large = 7
rounding_small = 5
