# wallpaper = HDMI-A-2, /home/suza/Pictures/wallpaper1.png
# wallpaper = DP-1, /home/suza/Pictures/wallpaper2.png

wallpaper {
	monitor = DP-1
	path = ~/.dotfiles/wallpapers/wallpaper1.png
	fit_mode = cover
}
