[[language]]
name = "sourcepawn"
language-id = "sourcepawn"
scope = "source.sourcepawn"
file-types = ["sp", "inc"]
comment-token = "//"
indent = {tab-width = 4, unit = "  "}
language-servers = ["sourcepawn-studio"]

[[grammar]]
name = "sourcepawn"
source = { git = "https://github.com/nilshelmig/tree-sitter-sourcepawn", rev = "f2af8d0dc14c6790130cceb2a20027eb41a8297c" }

[language-server.sourcepawn-studio]
command = "sourcepawn-studio"

[language-server.sourcepawn-studio.config]
compiler.path = "/home/suza/Coding/SourcePawn/spcomp"
includeDirectories = ["/home/suza/Coding/Sourcepawn/Scripts/Include"]

[[language]]
name = "typst"
auto-format = true
formatter.command = "typstyle"
formatter.options = ["--column", "100"]

[language-server.tinymist]
command = "tinymist"

[language-server.tinymist.config]
preview.background.enabled = true
preview.background.args = ["--data-plane-host=127.0.0.1:23635", "--invert-colors=never", "--open"]
exportPdf = "onType"
