keep-open=always                                # Don't close the player after finishing the video,
                                                # and playback will never automatically advance to the next file in the playlist
reset-on-next-file=pause                        # After playing the next file in the playlist,

gpu-api=vulkan
hwdec=auto
