hl.env("HYPRCURSOR_THEME",  "theme_HackneyedCursors")
hl.env("HYPRCURSOR_SIZE",   "24")
hl.env("XCURSOR_THEME",     "xcursor_hackneyed_dark_24px")
hl.env("XCURSOR_SIZE",      "24")
hl.env("QT_CURSOR_SIZE",    "24")
hl.env("GDK_BACKEND",              "wayland,x11,*")
hl.env("QT_QPA_PLATFORM",          "wayland;xcb")
hl.env("QT_STYLE_OVERRIDE",        "kvantum")
hl.env("SDL_VIDEODRIVER",          "wayland,x11")
hl.env("MOZ_ENABLE_WAYLAND",       "1")
hl.env("ELECTRON_OZONE_PLATFORM_HINT", "wayland")
hl.env("OZONE_PLATFORM",           "wayland")
hl.env("XDG_SESSION_TYPE",         "wayland")
hl.env("XDG_CURRENT_DESKTOP",      "Hyprland")
hl.env("XDG_SESSION_DESKTOP",      "Hyprland")

