# ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
# ┃                     Monitor Configuration                   ┃
# ┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛

# Monitor wiki https://wiki.hyprland.org/0.45.0/Configuring/Monitors/

# monitor = HDMI-A-2, 1920x1080@74.97, 0x0, 1, transform, 3
monitor = DP-1, 1920x1080@144, 0x0, 1

# If you need to scale things like steam etc, please uncomment these lines.
# Adjust GDK_SCALE accordingly to your liking.
#xwayland {
#  force_zero_scaling = true       # Unscale XWayland
#}

#env = GDK_SCALE, 1.25                   # GDK Scaling Factor
